### ISSUE TITLE
How to reinterpret_cast a matrix?

### ISSUE THREAD

**Issue by chaoming0625** [dfm/extending-jax#3]
Dear @dfm , your tutorial is excellent. But I am not familar with c++. I have a naive question. 

You said that how to receive input values by:

>
> #include \<cstdint\>  // int64_t
> 
> template \<typename T\>
> void cpu_kepler(void *out, const void **in) {
>   const std::int64_t size = *reinterpret_cast<const std::int64_t *>(in[0]);
>   const T *mean_anom = reinterpret_cast<const T *>(in[1]);
>   const T *ecc = reinterpret_cast<const T *>(in[2]);
> }
> 

However, if one of my input values is a matrix, how can I ``reinterpret_cast`` it? 

Thanks.

**Comment by dfm** [comment]
The parameters will always be raw pointers, even if they are defined as matrices or tensors in Python. So if you need more structure, you'll have to pass all the necessary parameters (e.g. strides) to your function as extra input parameters, and then use those to index your pointer appropriately. The example here works with any shape of input parameters, but just treats them as flat and aligned.

The logic for how this is handled is all in the XLA translation rule:

https://github.com/dfm/extending-jax/blob/77c3466175c5d9d1361be79ec6c005684c67897b/src/kepler_jax/kepler_jax.py#L59-L130

Hope this helps!

**Comment by chaoming0625** [comment]
Dear @dfm , thank you very much.
