### ISSUE TITLE
XLA register translation rule fail

### ISSUE THREAD

**Issue by llCurious** [dfm/extending-jax#5]
Hey, i try to add custom call and define the xla translation rule follow this doc https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html#xla-compilation-rules

However, it miss the custom call part. And i try to implement this part follow your example code.

You use `functools.partial(translation, platform="cpu)` here, however, i got `func_wrapper() got an unexpected keyword argument 'platform'`
https://github.com/dfm/extending-jax/blob/main/src/kepler_jax/kepler_jax.py#L190-L193

Could you please give some suggestions?

P.S. I use Cython to implement the C++ XLA custom call function. And the only remaining part is register the xla translation rule.

**Comment by dfm** [comment]
That `platform="cpu"` in the translation rule is specific to this tutorial, where we write one function that can generate the translation rule for both the GPU and CPU:

https://github.com/dfm/extending-jax/blob/77c3466175c5d9d1361be79ec6c005684c67897b/src/kepler_jax/kepler_jax.py#L59-L62

In your case, you probably just have a single translation rule, so just forget the `partial`:

```python
xla.backend_specific_translations["cpu"][YOUR_PRIMITIVE] = YOUR_TRANSLATION_RULE
```
